---
title: "py-exceptiongroup"
layout: cache
categories: [package, develop-2025-02-23]
meta: {"compilers": ["gcc@=11.4.0"], "num_specs": 1, "num_specs_by_stack": {"hep": 1, "root": 1}, "oss": ["ubuntu22.04"], "platforms": ["linux"], "stacks": ["hep", "root"], "targets": ["x86_64_v3"], "versions": ["1.1.1"]}
spec_details: [{"compiler": "gcc@=11.4.0", "hash": "nib3alu4e7ob3kyghlnwadd5amdsluld", "os": "ubuntu22.04", "platform": "linux", "size": "-", "stacks": ["hep", "root"], "tarball": "https://binaries.spack.io/develop-2025-02-23/build_cache/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/py-exceptiongroup-1.1.1/linux-ubuntu22.04-x86_64_v3-gcc-11.4.0-py-exceptiongroup-1.1.1-nib3alu4e7ob3kyghlnwadd5amdsluld.spack", "target": "x86_64_v3", "variants": ["build_system=python_pip"], "versions": ["1.1.1"]}]
---